ptitSeb/gl4es

src/gl/pixel.c

Added conversion from GL_UNSIGNED_SHORT_1_5_5_5_REV to GL_UNSIGNED_SHORT_5_5_5_1, removed trailing spaces.

GL_UNSIGNED_SHORT_1_5_5_5_REV to GL_UNSIGNED_SHORT_5_5_5_1

---

src/gl/loader.h

This PR clarifies a bit the `loader.h` file by reuniting AmigaOS 4 and non-AmigaOS 4 builds.

Clarified the loader.h file

---

include/GL/gl.h
src/CMakeLists.txt
src/gl/attributes.h
src/gl/framebuffers.c
src/gl/init.c
src/gl/loader.c
src/gl/loader.h

This pull request adds preliminary emscripten support for gl4es.
Simple opengl program works, have not tested thoroughly though.

emscripten support

---

src/glx/hardext.c

Whoops, it looks like I forgot to test the changes I made in my last PR.

[GBM/DRM] Use the right names for functions in GetHardwareExtensions

---

Android.mk
src/CMakeLists.txt
src/agl/agl.c
src/agl/amigaos.c
src/gl/blit.c
src/gl/buffers.c
src/gl/build_info.c
src/gl/enum_info.h
src/gl/envvars.c
src/gl/envvars.h
src/gl/eval.c
src/gl/fpe_cache.c
src/gl/fpe_shader.c
src/gl/framebuffers.c
src/gl/getter.c
src/gl/gl4es.c
src/gl/glstate.c
src/gl/init.c
src/gl/listdraw.c
src/gl/listrl.c
src/gl/loader.c
src/gl/loader.h
src/gl/logs.c
src/gl/logs.h
src/gl/matrix.c
src/gl/pixel.c
src/gl/texture.c
src/gl/wrap/glstub.c
src/glx/glx.c
src/glx/hardext.c

Yo Seb! Trying to figure out how this stuff works. Looks as if I can only create a pull request which contains ALL the garba... errm valuable changes I made so far. And to make things worse, it apparently also includes stuff I included from you (although the last one wasnt done manually, so maybe git would get it right). Anyway, maybe you find it useful as is, otherwise dismiss :)

Log and EnvVar cleanup

---

include/GL/gl.h
src/CMakeLists.txt
src/gl/array.c
src/gl/attributes.h
src/gl/framebuffers.c
src/gl/init.c
src/gl/loader.c
src/gl/matvec.c
src/gl/wrap/gles.c
src/gl/wrap/glstub.c

basically just followed emscripten support in #114 , still need to be tested.

support for apple os

---

src/gl/init.c

Enable hardware test by default on Apple platforms

---

COMPILE.md
README.md

Add compilation/use guide for iOS

---

src/gl/fpe_shader.h
src/gl/framebuffers.c
src/gl/loader.c
src/gl/loader.h
src/gl/string_utils.h

Just some fixes for latest SDK.
I have been trying to get Neverball working on Emscripten. With gl4es, finally, it works! This is the only library that I found that implements all the needed fixed-function stuff AND works with Emscripten. There are no graphical glitches at all. Thanks!

Emscripten fixes

---

src/CMakeLists.txt
src/gl/arbconverter.c
src/gl/arbconverter.h
src/gl/getter.c
src/gl/gl_lookup.c
src/gl/init.c
src/gl/init.h
src/gl/oldprogram.c
src/gl/program.c
src/gl/shader.c
src/gl/state.h

This PR adds ARB support (may require more testing and fixes since my computer cannot use gl4es).

Added ARB support

---

src/gl/arbconverter.c

This PR fixes a case mismatch in ARB vertex shaders.

Case mismatch fix

---

CHANGELOG.md
MEDIA.md
README.md
USAGE.md

May others should remain, I fixed some detected by flyspell.
Signed-off-by: Philippe Coval <rzr@users.sf.net>
Change-Id: If62518d14924b93209af4fbee2441ff98fa7c47c

docs: Fix English mistakes

---

src/gl/arbparser.c

This PR fixes a problem reading signed constants in instructions.

Fixed an ARB parser problem

---

MEDIA.md

Thanks for your work @ptitSeb on gl4es! 
I was able to get the serious engine to a playable state! (Doubt I'll make more additions in the short term).
Added a gif and link to the MEDIA.md.

Add emscripten Serious Engine to media list.

---

CMakeLists.txt
src/CMakeLists.txt
src/egl/egl.c
src/egl/egl.h
src/egl/lookup.c
src/gl/gl_lookup.h
src/gl/loader.h
src/gl/logs.c
src/gl/logs.h
src/gl/raster.c
src/glx/hardext.h
src/glx/lookup.c

I add a new EGL wrapper to handle compatibility problems when using native EGL for GLES together with GL4ES wrapper.
Also add a new cmake option to decide whether to use Android log or not.

[EGL] add a new EGL wrapper.

---

src/glx/glx.c

---
The use of static memory here is undesirable/unacceptable for several
reasons:
a) if you take any QT-based application as example then MAX_CONFIG (to avoid
"static array looped") will have to be increased to 1500-2000;
b) when working with multithreaded programs, the "element capture" will
need to be surrounded by lock protections;
c) (the main thing) if you look at the documentation on glXChooseFBConfig
(for example here):
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glXChooseFBConfig.xml
we will see that the last sentence of the first paragraph of the section
'Description'says:
---cit---
Use XFree to free the memory returned by glXChooseFBConfig.
---end---
and most well-written programs do just that.
...
Including, by the way, gl4es itself - the resulting …

1. fix (remove static memory usage) in fillGLXFBConfig

---

src/gl/init.c
src/gl/pixel.c
src/gl/texture.h
src/glx/glx.c
src/glx/hardext.c

fix some spelling error

---

src/gl/fpe_shader.c

This seems to have slipped its way into the code, somehow

Fix[fpe-shader]: g_FragColor -> g**l**_FragColor

---

src/gl/buffers.c
src/gl/buffers.h
src/gl/gl4es.c
src/gl/list.c

Hey there, another small PR, the original commit author is @artdev but he asked me to open the PR for some reason.
Anyway, the PR addresses the implicit buffer deletion that seems up to the driver. 
It fixes the issue #381 
It addresses the issue #407 as well

Fix: Handle implicit buffer deletion

---

CHANGELOG.md
COMPILE.md
USAGE.md
src/agl/amigaos.c
src/gl/drawing.c
src/gl/fpe.c
src/gl/framebuffers.c
src/gl/glstate.c
src/gl/light.c
src/gl/line.c
src/gl/planes.c
src/gl/program.c
src/gl/shaderconv.c
src/gl/state.h
src/gl/stb_dxt_104.h
src/gl/texture.c
src/gl/texture.h
src/gl/texture_compressed.c
src/gl/texture_params.c
src/gl/texture_read.c
src/glx/gbm.c
src/glx/glx.h

No code has been touched, typos fixed solely in comments or error/warning output

JANITORIAL: Fix a few typos in comments

---

CHANGELOG.md
USAGE.md
src/gl/glstate.h
src/gl/program.c
src/gl/shader.c
src/gl/texture_params.c

program.c and shader.c have typos in variables (actualy_deleteshader and actualy_detachshader)
But i think i caught all of them
feel free to cherry-pick

JANITORIAL: Fix another small bunch of typos

---

src/gl/const.h
src/gl/shaderconv.c
src/gl/texture.c

small fixes needed for shaders to work in openmw and other conversions for opengl effects.
also adding GL4ES as a define in glsl files.

Small fixes
