ptitSeb/gl4es

- src/gl/shader.c
The glShaderSource function should allow the length array passed to it
to contain negative values. In this case the length value should not be
used, instead the string with the same index should be considered as a
NULL-terminated string.
The game Taisei calls glShaderSource in this way (all length values are
-1). This commit makes this game running well with gl4es and Mesa GLES2
driver.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
> [GLES2] allow glShaderSource to deal with negative length items

- src/gl/pixel.h
The widthalign macro fails to work on 64-bit platforms, as the width
might be considered as 32-bit (unsigned )int instead of 64-bit (u)intptr_t.
Fix this by force convert all reference of the parameters of the macro
to uintptr_t.
This fixes texture loading on x86_64 platform.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
> fix 64-bit pointer support for widthalign macro

- src/gl/shaderconv.c
When GL_EXT_frag_depth is present, the shader converter will try to add
a #extension sentence to enable it. However, it's wrongly placed after a
line of ordinary definition in the header, which makes the converted shader
grammarly error.
Fix this by insert the #extension sentence before the definition.
The sentences of GL_EXT_frag_depth used to lack a newline, and it's also
added in this commit.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
> [GLES2] fix the place of #extension when GL_EXT_frag_depth is present

- src/CMakeLists.txt
- src/gl/drawing.c
- src/gl/gl.c
- src/gl/pointsprite.c
- src/gl/stubs.c
- src/gl/texture.c
- src/gl/wrap/gl.c
- src/gl/wrap/gles.c
Something changed on Ubuntu, where the OpenGL module used to work just fine with gl4es (tested with 5.22). With current Ubuntu Perl 5.26, the OpenGL module links to additional symbols directly, without dynamic lookup. This results in "undefined symbol" errors and program abort.
Most annoyingly, the obsolete GL_ARB_vertex_program extension is among these new symbols. New file src/gl/stubs.c implements empty stubs that set a GL error.
A couple of additional symbols use their ...ARB/...EXT name, where just that alias is missing, so I added those in the corresponding files.
> Perl 5.26 OpenGL module on Ubuntu is missing symbols

- CMakeLists.txt
Added one option in the CMake, let gl4es can set default LIBGL_ES backend as GLES 2.0.
`cmake . -DDEFAULT_ES=2; make GL`
> Let DEFAULT_ES option can be supported in CMake

- src/glx/rpi.c
With my Pi 3B+ running Raspbian 9.6, every application I tested other than bloboats was showing the game window alpha-composited translucently over the Raspbian PIXEL desktop. Quite a distraction when attempting to play a full-screen game.
Passing alpha = 255 fixes this. Verified with eduke32 (USE_OPENGL=1), jfsw (USE_OPENGL=1), and minetest's main menu.
> rpi: use opaque window for dispmanx

- .gitignore
- COMPILE.md
- src/CMakeLists.txt
- src/gl/build_info.c
- src/gl/build_info.h
- src/gl/init.c
This PR adds the `build/` folder to the list of ignored folders, as well as update the `COMPILE.md` file to reflect the fact that you can now build in `build/`.
It also adds a file that will build automatically in order to always update the build time and date in the logging text when starting gl4es.
> Minor improvements

- .gitignore
- CMakeLists.txt
- test.cmake
- tests/test.sh
This PR features multiple automated test for CTest (it is the same as running `tests/tests.sh`, but doesn't stop when a test failed, reduces outputed text and outputs less files) and ignore all PNG inside the `tests/` root folder.
> Added CTest support

- test.cmake
- tests/test.sh
This PR features a better CTest implementation:
- Simplified the `run_test` macro usage in `test.cmake`
- Better error output when having verbose output
- Run all GLES test before failing the test
> Better CTest implementation

- src/gl/buffers.c
`void*` can be a typo: `bufferGetParameteriv()` doesn't return any value and its
return value is not used anywhere else.
> Fix bufferGetParameteriv return type

- src/gl/matvec.c
- src/gl/matvec.h
`float` can be a typo: `cross3()` doesn't return any value and its
return value is not used when invoked from `eval.c`.
> Fix cross3 return type

- src/glx/gbm.c
- src/glx/hardext.c
This uses `GBMOpenDisplay` to get the display in `getHardwareExtensions`.
It also adds a static variable to check whether LoadGBMFunctions has already run, and adds the `gbmdrm` prefix to `drmMoreRmFB`.
glxgears now runs, with the same performance as my wrapper (and the same problems).
> [GBM/DRM] Use GBMOpenDisplay to get display while getting extensions

- src/gl/fpe_shader.c
Workaround: AmigaOS4's W3D Nova doesn't support SPIR-V OpImageSampleProjImplicitLod, therefore OGLES2 cannot handle texture2Dproj here for now.
> Workaround for AmigaOS4

- tests/test.sh
This PR changes the way the test script behave when the test crash (segfault).
Note that every error output is treated as a standard output (meaning, as an error) -- if this adds problem, the `2>&1` part must be removed.
> Tests now fail when crashing

- CMakeLists.txt
- include/gl4esinit.h
- src/CMakeLists.txt
- src/gl/framebuffers.c
- src/gl/init.c
- src/gl/loader.c
- src/gl/loader.h
- src/glx/glx.c
This allows to disable library loading and set GetProcAddress implementation from application when it already created GLES context/surface and do not need any context management/loading from gl4es. This removes glx/* dependencies except hardext.c with NOEGL and NOX11 enabled
> Export API to set external GetProcAddress, getMainFBSize, allow disable library loader

- src/gl/init.c
- src/gl/loader.c
ifdef-typo in gl/loader.c (AMIGAOS64 instead of AMIGAOS4) and missing NO_GBM check in gl/init.c
> (Amiga) Fixes

- src/gl/arbconverter.c
- src/gl/arbgenerator.c
- src/gl/arbhelper.c
- src/gl/arbhelper.h
- src/gl/arbparser.c
This PR changes various things in the ARB shader generator:
- The samplers are now left to be declared by shaderconv ([TODO])
- The arrays are now initialized by iterating over the indexes instead of using an array constructor
- If the length of an array is not defined, automatically declare it
- Bug fixes in the `resolveOutput` function in vertex shaders
> Use of auto-declared `gl_Sampler`* in ARB shaders

- src/gl/arbgenerator.c
- src/gl/arbhelper.h
- src/gl/arbparser.c
This PR features:
- a new param support (`state.matrix.texture`)
- better `resolve`* error (now always printed instead of when in debug only)
- better generator: now the swizzle is done as soon as possible instead of as late as possible, giving `gl_TexCoord[1].y = R3.w;` instead of `gl_TexCoord[1].y = R3.wwww.y;`
> ARB parser upgrades

- src/gl/arbgenerator.c
This PR moves a variable declaration at the top of the switch (which is what was intended...) and removes unnecessary parenthesis in the `LG2` generation (going from `R1.x = ((log2(R1.x)));` to `R1.x = (log2(R1.x));`).
> Minor fixes

- src/gl/arbconverter.c
- src/gl/arbconverter.h
- src/gl/arbgenerator.c
- src/gl/arbgenerator.h
- src/gl/arbhelper.c
- src/gl/arbhelper.h
- src/gl/arbparser.c
- src/gl/arbparser.h
- src/gl/oldprogram.c
This PR removes dependencies to `state.h` from the files `arbconverter.c`, `arbgenerator.c`, `arbhelper.c` and `arbparser.c` (and sometimes include `config.h` to have `MAX_TEX`).
> Removed almost all dependancies to state.h in ARB converter

- src/gl/arbparser.c
This PR fixes a segmentation fault when a param is `state.matrix.texture[0]` (or any other number inside) or `state.matrix.matrixview[0]`.
> Fixed crash when having only `state.matrix.texture[0]` and similar

- src/gl/arbparser.c
This PR transforms the ARB vertex shader attribute `vertex.attrib[n]` into the GLSL variable `gl_VertexAttrib_n`.
> Added the ARB vertex shader attribute vertex.attrib

- src/gl/arbconverter.c
- src/gl/arbgenerator.c
- src/gl/arbparser.c
- src/gl/arbparser.h
This PR tries to have a correct handling of `result.fogcoord` in ARB shaders.
> Changed the way gl_fogFragCoord is handled

- src/gl/arbconverter.c
- src/gl/arbhelper.c
- src/gl/arbhelper.h
- src/gl/arbparser.c
This PR adds a correct support of the `ARB_fog_`* options in fragment shaders and a dummy support of `ARB_precision_hint_nicest`.
> Supported ARB options extension

- src/gl/oldprogram.c
This PR fixes the behavior of gl_ProgramStringARB when gl4es fails to convert the GLSL code into a compiled shader by adding a dummy error at address 0 (beginning of shader).
> Make the ProgramStringARB fail when failed to convert/compile

- CMakeLists.txt
Note files are installed into gl4es namespace to avoid overlap,
with system's opengl files.
This is useful for distro packagers
Signed-off-by: Philippe Coval <rzr@users.sf.net>
Change-Id: I3f2648b3c5da03693cf2a6bf47ae089bd207cee2
> cmake: Install lib and headers

- CMakeLists.txt
- src/CMakeLists.txt
This PR makes it so that `build_info.c` is only re-built when a header or processing unit is changed.
> [CMAKE] Make build_info only when necessary

- src/gl/arbparser.c
This PR adds sign support for single-value params, like `PARAM   subOne = { -1, -1, -1, -1 };`.
> Added sign support for single-value params

- src/gl/arbparser.c
This PR fixes two errors:
- the first one is when having a constant inside an instruction (though it is *technically* not in the [official(?) documentation](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_fragment_program.txt));
- the second one is when trying to initialize a single-value parameter with two values.
> Fixed two errors

- src/gl/arbconverter.c
- src/gl/arbparser.c
- src/gl/arbparser.h
This PR fixes the `result.depth` fragment ARB variable, that should be mapped to the `(*, *, gl_FragDepth, *)` vector (and adds scalability of such special cases).
> Fixed gl_FragDepth in the ARB converter

- src/gl/arbgenerator.c
This PR fixes the `MIN`, `MAX` and `MAD` instructions when called with a constant as second/third values.
> Fixed some ARB instructions generation

- CMakeLists.txt
- include/EGL/egl.h
- include/EGL/eglext.h
- include/EGL/eglplatform.h
- src/gl/framebuffers.c
- src/gl/init.c
- src/gl/samplers.c
- src/glx/glx.c
A small set of 3 patches to make the library build on the GCW-Zero, which does not use X11 but KMS/DRM directly, uses uClibc instead of glibc, and Etnaviv as its GPU driver.
> No-X11 / uclibc build fixes

- src/gl/preproc.c
This PR fixes the preprocessor with numbers such as `1e10` (#213 and #215).
> Fix of the preprocessor with exponential notation

- src/gl/fpe.c
Found when running the Serious Engine against gl4es.
> Add missing initialization of texenvalphascale

- src/gl/init.c
`agl_reset_internals` is only available with AMIGAOS4
Apologies for spurious trailing whitespace removal
> Fix non-Amiga GL4ES_COMPILE_FOR_USE_IN_SHARED_LIB

- src/gl/init.c
Better solution to https://github.com/FWGS/xash3d-fwgs/pull/255
> Fix crash on unload with NO_INIT_CONSTRUCTOR

- include/gl4esinit.h
- src/gl/gl_lookup.c
- src/gl/init.c
1. Add `__attribute__((visibility("default")))` to all public functions.
2. Expose `close_gl4es()`.
3. Make public header C++-compatible.
> Fixup public functions

- include/gl4esinit.h
Fixes the following error when compiled with `-Werror=strict-prototypes`
```
gl4es/include/gl4esinit.h:16:1: error: function declaration is not a prototype [-Werror=strict-prototypes]
16 | void close_gl4es();
| ^~~~
```
> gl4esinit.h: Fix -Werror=strict-prototypes

- src/gl/shaderconv.c
I've noticed that converting GLSL 1.20 to GLSL ES 300+, does not convert `attribute` and `varying`, it caused these compile errors:
```
'attribute' : Illegal use of reserved word
'varying': Illegal use of reserved word
```
So, I added macros to automatically replace them to `in` and `out`.
> [GLSL ES 300] Add macros for GLSL compatibility

- include/GL/glx.h
This change follows https://github.com/ptitSeb/gl4es/blob/c3c172dc098dbd379420a3111b1142c4d7fbddd7/src/glx/utils.h#L4-L7
So it should fix build problems for targets that is:
1. Android with X11 support (maybe, some day)
2. Other non X11 platforms that isn't Android
> Replace "ifndef ANDROID" with "ifndef NOX11" for X11 support in "include/GL/glx.h"

- src/gl/framebuffers.c
I got an error with Valgrind because the deleted framebuffer was still bound.
> Unbind framebuffer, if it is bound, before freeing it

- src/gl/texture.c
This is a tentative fix for #374.
When the depth data provided by the application a GL_UNSIGNED_INT is expected if depth24 is supported although GL_UNSIGNED_SHORT is provided.
In addition, no conversion is supported for depth buffers.
> Don't upgrade depth to GL_UNSIGNED_INT when GL_UNSIGNED_SHORT is given

- src/gl/arbparser.c
GCC 11.2 is a bit paranoid about these declarations and goes into some recursive warning loop and never explains what was wrong on that line. I added some brackets, and it helped to avoid the flood
```
[ 60/415] Compiling ref_gl/gl4es/src/gl/arbparser.c
../ref_gl/gl4es/src/gl/arbparser.c: In function ‘readNextToken’:
../ref_gl/gl4es/src/gl/arbparser.c:36:9: note: switch starts here
36 |         switch (*curStatus->codePtr) {
|         ^~~~~~
../ref_gl/gl4es/src/gl/arbparser.c:137:23: note: ‘exp’ declared here
137 |                 float exp = 0.1f;
|                       ^~~
../ref_gl/gl4es/src/gl/arbparser.c:36:9: note: switch starts here
36 |         switch (*curStatus->codePtr) {
|         ^~~~~~
../ref_gl/gl4es/src/gl/arbparser.c:137:23: note: ‘exp’ declared here
137 | …
```
> arbparser: add brackets to case blocks where variables are declared, to prevent warnings spam on GCC

- src/egl/egl.c
- src/egl/egl.h
- src/egl/lookup.c
- src/gl/loader.h
SDL2 on the ODROID Go Ultra requires fences and a few reverse engineered libmali internals in order to initialize an EGLSurface using ION-backed framebuffers.
These are used in order to achieve fast, zero-copy frame presentation using the GE2D hardware blitter.
> Add necessary OGU EGL wrapper functions.

- src/gl/shaderconv.c
On Visual Studio C++ compiler, we cannot use variable length array. Use `_alloca` instead here.
> fix: fix shaderconv compile on MSVC

- src/gl/wrap/glstub.c
Stubbed functions were querying an environment variable per call, which could greatly reduce framerate.  I think globals4es.silentstub is the right state to be checking instead.
> Fix significant performance hit on stubbed functions 

- src/gl/fpe_shader.c
When t == 0. would cause a bad memory index
> Fix bad index in fpe_VertexShader

- src/glx/glx.c
Shoutout to the compiler for finding it:
```
gl4es/src/glx/glx.c:2514:56: warning: array index 1 is past the end of the array (which contains 1 element) [-Warray-bounds]
return addPBuffer(Surface, Width, Height, Context, Config[1]);
^      ~
gl4es/src/glx/glx.c:2470:5: note: array 'Config' declared here
EGLConfig Config[1];
^
```
> Fix Config[1] out of bounds in gl4es_glXCreatePbuffer

- src/gl/shaderconv.c
Hi Seb, I realized that one string allocation was never freed after a shader has been converted.
This PR fixes a 51 bytes memory leak that could happen when converting a shader.
> Fix[shaderconv]: Small memory leak

- src/gl/fpe.h
- src/gl/framebuffers.c
Hello once again !
I've recently migrated my build system to ndk 26-rc1 and uncovered two issues thanks to the updated compiler.
> Fix[framebuffer, fpe]: code typos

- src/gl/buffers.c
gl4es_glMapNamedBuffer seems to have wrong linkage by mistake
>  Fix wrong attribute when GLES_SOFTFLOAT defined

- src/gl/gl4es.c
#364 was closed but not completely fixed. This fixes the last undefined symbol error.
> Fix Emscripten "undefined symbol: glCallList"

- src/egl/egl.c
- src/egl/egl.h
- src/egl/lookup.c
- src/gl/loader.h
Needed by mali-fbdev SDL2 backend for certain sunxi h700 devices (rg28xx, rg40xx).
> Export eglDestroySyncKHR symbols.

- src/gl/enable.c
- src/gl/init.c
- src/gl/loader.c
- src/gl/texture.c
- src/gl/texture_params.c
- src/gl/wrap/gles.c
+ DEFAULT_GLES, DEFAULT_EGL compile defines for loader to let user build with extra non-common GLES and EGL lib names
* Changed tabs->spaces for consistency
+ LIBGL_FB compile define used if user has not set env variable - allow to define default LIBGL_FB value at compile time
* added defines to fix older C99 errors about struct typedef redefinitions
* added missing implementations of gl functions: `glTexParameteri`, `glGetBooleanv`, `glIsEnabled`
> DEFAULT_GLES, DEFAULT_EGL, LIBGL_FB compile defines

- include/EGL/eglplatform.h
- src/gl/fpe.c
- src/gl/fpe.h
- src/gl/fpe_cache.c
- src/gl/fpe_cache.h
- src/gl/framebuffers.c
- src/gl/glstate.h
- src/gl/init.c
- src/gl/oldprogram.c
- src/gl/program.h
- src/gl/shader.h
* Moved header order
* Add local define guards for headers to avoid C99 typedef redefinition error
* tabs->spaces
* Add EGL support for QNX NTO platform
* glTexParameteri calls fixed to use gl4es wrapper
> resolving typedef errors for C99 and add EGL support for QNX NTO
